apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-cluster
  namespace: openshift-operators
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: us-east-1/dev-1/ingress
    repoURL: https://github.com/David-Igou/openshift-environments.git
    targetRevision: HEAD
  syncPolicy: {}
