apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-cluster
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: us-east-1/dev-1/monitoring
    repoURL: https://github.com/David-Igou/openshift-environments.git
    targetRevision: HEAD
  syncPolicy: {}
