apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "https://github.com/David-Igou/openshift-cluster-app-templates.git/ingress/?ref=lab"
namespace: openshift-ingress-operator
commonAnnotations:
  env: lab
patches:
  - patch: |-
      apiVersion: operator.openshift.io/v1
      kind: IngressController
      metadata:
        name: sharded
      spec:
        domain: "*.apps.lab-1.us-east-1.igoucorp.com"
    target:
      name: sharded
